default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: auth_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: auth_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: auth_production
  username: auth
  password: <%= ENV["AUTH_DATABASE_PASSWORD"] %>
